# Generated by Django 3.1.2 on 2020-11-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(default='', max_length=5000)),
                ('name', models.CharField(default='', max_length=5000)),
                ('email', models.EmailField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=5000)),
                ('city', models.CharField(default='', max_length=5000)),
                ('state', models.CharField(default='', max_length=5000)),
                ('zip_code', models.CharField(default='', max_length=7)),
            ],
        ),
    ]
