# Generated by Django 3.1.2 on 2020-11-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='id',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='update_desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='update_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
